version: '3.9'

services:
  # Main client
  ds-portfolio:
    container_name: ds-portfolio
    build: .
    volumes:
      - .:/usr/src/ds-portfolio
    ports:
      - 3000:3000
    # stdin_open: true
    restart: always
    command: npm run devStart
